---
user: openproject
group: openproject
description: OpenProject
homepage: https://www.openproject.org
maintainer: operations+packaging@openproject.com
license: GPL
targets:
  debian-9:
    build_dependencies: &1
    - libsqlite3-dev
    dependencies: &2
    - unzip
    - poppler-utils
    - unrtf
    - tesseract-ocr
    - catdoc
    - imagemagick
  debian-10:
    build_dependencies: *1
    dependencies: *2
  debian-11:
    build_dependencies: *1
    dependencies: *2
  ubuntu-16.04:
    build_dependencies: *1
    dependencies: *2
  ubuntu-18.04:
    build_dependencies: *1
    dependencies: *2
  ubuntu-20.04:
    build_dependencies: *1
    dependencies: *2
  centos-7:
    env:
    - BUNDLE_BUILD__PG="--with-pg-config=/usr/pgsql-13/bin/pg_config"
    - NODE_ENV=production
    - NPM_CONFIG_PRODUCTION=false
    dependencies: &3
    - epel-release
    - ImageMagick
    - unzip
    - poppler-utils
  centos-8:
    env:
    - NODE_ENV=production
    - NPM_CONFIG_PRODUCTION=false
    dependencies: *3
  sles-12:
    build_dependencies:
    - sqlite3-devel
    - ImageMagick
before_precompile: packaging/setup
after_precompile: packaging/teardown
services:
- postgres
installer: https://github.com/pkgr/installer.git
wizards:
- https://github.com/pkgr/addon-legacy-installer.git
- "./packaging/addons/openproject-edition"
- https://github.com/pkgr/addon-postgres
- https://github.com/pkgr/addon-apache2.git
- "./packaging/addons/repositories"
- https://github.com/pkgr/addon-smtp.git
- https://github.com/pkgr/addon-memcached.git
- "./packaging/addons/openproject"
buildpack: https://github.com/opf/heroku-buildpack-multi.git#master
env:
- NODE_ENV=production
- NPM_CONFIG_PRODUCTION=false
:description: OpenProject
:name: openproject
:vendor: Packager.io <https://packager.io>
:maintainer: operations+packaging@openproject.com
:version: 12.1.4
